---
title: "Wild Data"
format: html
editor: visual
execute: 
  warning: false
  messages: false
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
mack_verts <- read_csv(here::here("data", "AS00601.csv")) %>%
  clean_names()
```

```{r}
mc_wt_5 <- mack_verts$weight[5]
mc_wt_5

mc_length_8_20 <- mack_verts$length1[8:20]
mc_length_8_20

mc_dates <- mack_verts$sampledate
mc_dates
```

Create subset of mack_verts data for DITE

```{r}
mc_salamanders <- mack_verts %>% filter(species == "DITE")
```

```{r}
ggplot(data = mc_salamanders, aes(x = length1, y = weight)) +
  labs(x = "Snout-Vent Length (ml)",
       y = "Snout-Vent Weight (g)",
       title = "Salamander Size",
       caption = "https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-and.4027.14" ) +
  geom_point(color = "purple")

ggsave(here("figs", "salamander_size.png"),
       width = 6,
       height = 5)

```

Create subset of mack_verts data for ONCL

```{r}
mc_trout <- mack_verts %>% filter(species == "ONCL")
```

```{r}
ggplot(data = mc_trout, aes(x = length1, y = weight)) +
  labs(x = "Snout-Vent Length (ml)",
       y = "Snout-Vent Weight (g)",
       title = "Cutthroat Trout Size",
       caption = "https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-and.4027.14" ) +
  geom_point(aes(color = reach, alpha = 0.5)) +
  facet_wrap(~reach) +
  scale_color_manual(values = c("blue", "red", "purple"))

```

```{r}
ggsave(here("figs", "cutthroat_size.png"),
       width = 6,
       height = 5)
```
